### ISSUE TITLE
Accessibility of Paris' subway network

### ISSUE THREAD

**Issue by oargueso** [jsoma/playfair-projects#103]
After analyzing how wheelchair-friendly NYC's and Madrid's undergrounds are, I want to add Paris to the equation. I have already downloaded the data (as a .csv) from [RATP's website](http://data.ratp.fr/explore/dataset/accessibilite-des-gares-et-stations-metro-et-rer-ratp/), and I have obtained from them the documentation to correctly interpret the codes they use.

As in my previous project about Madrid (Pitch #20), I would like to create a map in which the non-accessible stations are removed. This could be complemented with other kind of graph (bar charts?).

**Comment by snajmabadi** [comment]
Really like the idea! Maybe as you continue to look at the accessibility of subway networks in various countries, you could create a bar chart showing the most/least accessible subway networks based on percent of total subway stops that are accessible).

**Comment by jsoma** [comment]
👍  I like that you've got a theme going!

**Comment by jsoma** [comment]
Story opened, closing
