### ISSUE TITLE
Violence in social conflicts in Central America and Africa

### ISSUE THREAD

**Issue by paolorivas** [jsoma/playfair-projects#110]
Violent confrontations within sovereign states in Africa an Central america follows similar patterns according to the type of actor involved. According to data collected from more than 24 years of social conflicts in this two regions, the shorter and Violent is a social conflict, and the less the government is involve with it, the more violent and deathly it gets. I would like to use correlations and maybe a linear regression to explore number of deaths related to kind of conflict.

Link of the data:
https://www.strausscenter.org/scad.html
# Pitch issue checklist

Paste this into the body of your pitch issue, NOT as the first comment! You can delete this line after you paste it.
- [ ] My pitch issue has `[Pitch]` in the title
- [ ] My pitch issue has `[Data request]` in the title if I need additional data
- [ ] My pitch issue links to my data set
- [ ] My pitch issue explains what I'd like to explore in the data set
- [ ] My pitch issue includes multiple possible headlines
- [ ] My pitch issue includes any links/images I'm using as inspiration
- [ ] My pitch issue includes appropriate labels in the title such as `[Pitch]` and maybe `[Data Request]`
- [ ] I have received two comments of peer feedback on my pitch issue
- [ ] I have received editorial feedback on my pitch issue
- [ ] My pitch has been approved

**Comment by jayjgal** [comment]
Paolo do you mean to say that social conflicts are more deadly when they are directed at the government, or less? I see that they have some interesting analyses in their publications about how protests and other conflicts are directed more at the government, as opposed to other groups, as the government's share of GDP rises.

**Comment by barjacks** [comment]
Interesting data set. How about comparing the two continents for differences of social conflicts? Are their typical S. American pattern, and typical patterns from other countries? What you could also do, is to map out deaths per 100'000 (or whatever size makes sense) resulting from social conflicts in all S.American countries with the data.
