### ISSUE TITLE
DJL: Shoppers Clicking Behavior regarding eShopping Banner

### ISSUE THREAD

**Issue by djlee0202** [jsoma/playfair-projects#111]
## Intro

 eShoppers usually see banner when they get in the webpage(Frontpage), search for specific product(Search page), or click on categories (Category page). Online shoppers tend to behave as follows when they purchase a product from the online website. In most case, circled path is the key point which they get exposed to Banner Advertisement.

![path_to_purchase](https://cloud.githubusercontent.com/assets/19519829/17303697/be5b94c2-57ef-11e6-8fdb-68a4b16a5538.png)

For detail terminology, please check below.
http://whatis.techtarget.com/reference/advertising-terminology-on-the-Internet 

## Analysis.

**1.  Depends on the product, there is a different tendency on when consumers tend to gain interest on Ads (beginning or during the Ad Campaign), but they lose their interest significantly after two weeks.**

![click rate versus time](https://cloud.githubusercontent.com/assets/19519829/17297847/6d4ea0a2-57d5-11e6-8a67-199f73561822.png)

### Sample Website Banner Composition

The website is providing 12 banners at Front Page, Search Page, and Category Page.
(1) Front Page
![mainpage](https://cloud.githubusercontent.com/assets/19519829/17295825/38ad4a28-57cc-11e6-8c5b-2da5e2c14ff5.png)

(2) Category Page and Search Page
![category](https://cloud.githubusercontent.com/assets/19519829/17295828/3a46ebe6-57cc-11e6-8114-b4c72588dd8b.png)

### Data Set
By following Steve's advice(Thank you, Steve), I was able to get the sample data from the online shopping website company by simply emailing them. They provided result of 8 advertisement campaign with no additional information regarding product. The data was provided only for academic purposes.

Based on the data provided by the  mall, I am planning to analyze the relationship between clicking rate, banner type as well as time. The following is the data which I got from the shopping mall. 
![image](https://cloud.githubusercontent.com/assets/19519829/17114381/9ee04ffc-527c-11e6-8135-4b2bf60772fa.png)

==================
### Data Dictionary

As shown above, there are 7 columns in the dataset.
The following are explanation of the Data Column.

1. Project : Advertisement of the product
2. Banner number: Location of the banner (Explained above.)
3. Date passed : the number of date passed after Ads been posted
4. Impression : the number of ad popped to customers
5. Click : the number of click to banner
6. CTR : Click / impression (i.e. Efficiency)

# Story issue checklist
My pitch was (use the number): #47

- [x] My pitch has been approved (see `PITCHING.md`)
- [x] My story issue links to my pitch issue
- [x] I link to my finalized (ish) data source(s)
- [x] I've included a brief summary of my story
- [x] I've included some possible headlines or findings
- [x] I've included some links or images as inspiration (if you have any)
- [x] I have received two comments of peer feedback
- [x] I've included an update of my visualization/story in a comment
- [x] I have received two comments of peer feedback after posting an update
- [x] I have received editorial feedback

**Comment by radhikapc** [comment]
Wow ! Impressive story. It's really great that you went ahead and asked for data set and they agreed. would love to see the results

**Comment by spm2164** [comment]
Definitely some interesting threads in this project, although I don't know how you will eventually tie it all together. Maybe a writeup of a recommendation to vendors on how to advertise successfully on the website? That won't be a visualization, but maybe you don't have to worry about it.

**Comment by palrogg** [comment]
Does the ad society have a fixed pricing? Maybe it could be interesting to have a "price/CTR" ratio based on this. I wonder if some cheap ad placement can have a good CPC (cost per click), and if the most expensive ad placement are really worth it with current prices...

**Comment by djlee0202** [comment]
Final Outcome
![datastudio_prj02](https://cloud.githubusercontent.com/assets/19519829/17647104/ebfe5b5a-61b1-11e6-95e8-68d4bfe342e4.png)
