### ISSUE TITLE
NY Prison Population

### ISSUE THREAD

**Issue by snajmabadi** [jsoma/playfair-projects#12]
Dataset: https://data.ny.gov/Public-Safety/Inmates-Under-Custody-Beginning-2008/55zc-sp6m

I intend to explore NY's prison population using the data set above, focusing on any trends in age, gender, most serious crime and county of indictment. After analysing the data set, I will see if there are commonalities based on county of indictment or age and, if so, if those commonalities could be reflective of broader policies.

**Comment by barjacks** [comment]
I would spend some time looking around to see who else has worked with this really interesting data set.

**Comment by jsoma** [comment]
Story created, closing
