### ISSUE TITLE
The vast majority of campaign cash come from small individual contributions

### ISSUE THREAD

**Issue by jayjgal** [jsoma/playfair-projects#137]
[Data](http://www.fec.gov/finance/disclosure/ftpdet.shtml#a2015_2016) from the Federal Election Commission show that the largest source of campaign funds for both candidates comes in the form of contributions of less than $3,000 made by individual donors. The data show that through June of this year, roughly 10 times as many individuals contributed to Hillary Clinton's campaign, compared to Donald Trump's. This story will provide a general look at where campaign funds come from and provide a foundation to get into more complex issues like campaign bundlers and the role of political action committees and superPacs in the presidential election.  In the images below, I plot the amount and frequency of all individual contributions received by each of the candidate's campaign committees. 

Possible headlines:
Clinton's individual contributors outnumber Trump's by a factor of 10
The majority of campaign funds come from small donations, many of them less than $200
![clinton_output](https://cloud.githubusercontent.com/assets/19531200/17367857/aed0e964-595f-11e6-9ad2-9b5753c4a5a4.png)
![trump_output](https://cloud.githubusercontent.com/assets/19531200/17367858/afbe3700-595f-11e6-9b51-3f5269f570ed.png)
# Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [ ] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [x] My pitch issue includes multiple possible headlines
- [x] My pitch issue includes any links/images I'm using as inspiration
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by juneeseo** [comment]
The graphic is very effective to show patterns and density of donations but it would be also helpful to have number of total donators and total $ raised in the graphic!  And i was wondering if this difference in donation pattern is due to the difference in donation channel.......? anyway it is very interesting to look at.

**Comment by barjacks** [comment]
Interesting. Can you explaining why certain amounts are so much more frequent than others. Would be a useful annotation of the graph. And I'm sure you can make the graphs look a lot prettier than thay look now :-) But really great idea somewhat surprising result that the gap is so big between candidates.
