### ISSUE TITLE
Utah homeless gains exaggerated

### ISSUE THREAD

**Issue by kbennion** [jsoma/playfair-projects#147]
I found the source data! (http://www.aei.org/wp-content/uploads/2016/03/Utah-Homelessness.pdf)
I'd like to do another version of this chart:
![image](https://cloud.githubusercontent.com/assets/19495803/17373225/43a7ab44-5975-11e6-9817-5ca80185da8e.png)
but with percentage of overall population instead of number of homeless.
# Story issue checklist

My pitch was (use the number): #101 
- [ ] My pitch has been approved (see `PITCHING.md`)
- [ ] My story issue links to my pitch issue
- [ ] I link to my finalized (ish) data source(s)
- [ ] I've included a brief summary of my story
- [ ] I've included some possible headlines or findings
- [ ] I've included some links or images as inspiration (if you have any)
- [ ] I have received two comments of peer feedback
- [ ] I've included an update of my visualization/story in a comment
- [ ] I have received two comments of peer feedback after posting an update
- [ ] I have received editorial feedback

**Comment by kbennion** [comment]
(Here is a visual to get a sense of how population has grown.)
![image](https://cloud.githubusercontent.com/assets/19495803/17373803/db0e1016-5977-11e6-94a2-043dfe4f3678.png)

**Comment by mercybenzaquen** [comment]
I like that you are taking this graph as an inspiration and giving it your own twist. I would suggest you to use annotation to give us more info about why are we seeing a decrease. What happened around 2014? I think this is very interesting 👍

**Comment by skkandrach** [comment]
This is a really interesting topic! I agree with Mercy, more annotation or a legend included would be helpful for the user to depict what exactly is going on and better understand the correlation (if any).

**Comment by snajmabadi** [comment]
This sounds really interesting and I am excited to see how it turns out! I know you are working on trying to make a single graph with a double y-axis -- I wonder if it may be easier to just plot two graphs (one with a right aligned y-axis, and one left aligned) in matplotlib with the same figsize, and then just drag them on top of each other in Illustrator?

**Comment by snajmabadi** [comment]
Also, you mentioned some changes in the way the data collection was done/classified -- maybe make it an annotation if you can't account for the change?

**Comment by jsoma** [comment]
Could we get an image of what you're working on? It looks like both of those are from publications?

**Comment by kbennion** [comment]
Okay, I ended up collecting the information from the point-in-time homeless counts for each year, created a dataframe with those and population over time, and used it to graph the homeless population and how it compares as a percentage of the state's population.
![homeless](https://cloud.githubusercontent.com/assets/19495803/17495204/2c5c05d8-5d86-11e6-8cf3-3c157372ef4b.png)
