### ISSUE TITLE
Silicon Valley Dodges the Financial Crisis 2008 !

### ISSUE THREAD

**Issue by radhikapc** [jsoma/playfair-projects#160]
San Jose is the capital city of Silicon Valley, and it has been growing in terms of population, number of immigrants and housing. I am trying to explore two data sets, Median Home Price and Monthly Apartment rent over last 12 years which I got from San Jose Open Data portal:

http://data.sanjoseca.gov/dataviews/229980/median-home-prices/ 
http://data.sanjoseca.gov/dataviews/229966/average-monthly-apartment-rent/
![monthly-rent](https://cloud.githubusercontent.com/assets/3285001/17555209/b431b000-5edc-11e6-8a77-5fab2c8176ae.png)

To my surprise, there is no fall housing rental during the great financial crisis in 2008. To probe further, I explored the data on median income over years, and found a similar pattern: there is no dip in median income in 2008.

San Jose Open Data portal gives an API, which I would love to experiment: http://data.sanjoseca.gov/developers/
In the course of exploring the dataset, I might end up looking at the immigrant data set also to check if there is a correlation!

![monthly-rent-line](https://cloud.githubusercontent.com/assets/3285001/17555199/a8900f62-5edc-11e6-8204-eda5034402d2.png)
![median-income](https://cloud.githubusercontent.com/assets/3285001/17653562/49bcb274-6265-11e6-9a2b-b20c42637369.png)
### Story Issue Checklist

My pitch was (use the number): #160
- [ ] My pitch has been approved (see `PITCHING.md`)
- [ ] My story issue links to my pitch issue
- [ ] I link to my finalized (ish) data source(s)
- [ ] I've included a brief summary of my story
- [ ] I've included some possible headlines or findings
- [ ] I've included some links or images as inspiration (if you have any)
- [ ] I have received two comments of peer feedback
- [ ] I have received editorial feedback

**Comment by barjacks** [comment]
Love the idea. And very topical at the moment, with the whole immigrant discussion. Will you be able to work out differences of immigrants? Is it only rich, affluent tech people move to San José, or is the city attracting other people as well?

**Comment by paolorivas** [comment]
It would be interesting to see it in a map! I don't know if its possible, but it would give a better image on how expensive thing are over there!

**Comment by djlee0202** [comment]
I agree with Barney's idea. Additionally if you show the difference of the population of people (and their characteristics) and  find the relationship between them, that probably can explain the reason why the rent goes up.

**Comment by honjy** [comment]
Like Barney said, this is really timely! I'd love to find out why there were dips in housing prices. Also I'd look at inflation rates to see if that's the reason why housing prices have been increasing by so much!
