### ISSUE TITLE
DJL:Does the size of the street affect the usage of the Citibike?

### ISSUE THREAD

**Issue by djlee0202** [jsoma/playfair-projects#167]
Inspired by the article below, I am going to analyze the usage of the Citibike in Manhattan.
(Detail Analysis of Citibike usage in Manhattan)
http://toddwschneider.com/posts/a-tale-of-twenty-two-million-citi-bikes-analyzing-the-nyc-bike-share-system/

Many transportation such as Buses and subways are concentrated on the 42nd street and many other wide street. How about the Citi Bike? I am planning to make some calculation the Citi Bike usage (the number of pickup plus the number of return on each citi bike hub) on different streets. The following the simple calculation made by excel sheet. The result demonstrates that usage peak is in around 10 ­ to 30th streets.

![citibikeusage](https://cloud.githubusercontent.com/assets/19519829/17466165/6123dd4a-5cd7-11e6-9cb7-788696f0746f.png)

 I would like to find out the distribution of Citibike usage and relationship between the width of the street.

Data Source/Data Set : https://s3.amazonaws.com/tripdata/index.html
# Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [x] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [x] My pitch issue includes multiple possible headlines
- [x] My pitch issue includes any links/images I'm using as inspiration
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by djlee0202** [comment]
![citibike-01](https://cloud.githubusercontent.com/assets/19519829/17466241/3d4eae5c-5cd9-11e6-84dc-5327c0e7136e.png)

Quick visualization made by Excel. 
Hopefully I can replicate this with Python/Illustrator.

**Comment by gcgruen** [comment]
What a cool idea!!! I totally dig it. One thought: Maybe it doesn't necessarily link to street width but rather/also to the presence of [bike lanes](http://www.nycbikemaps.com/)? So, once we are into mapping that could be an addition or follow-up and add into the narrative of "hey NYC, if you want your people to use more bikes, make your streets wider/introduce bike lanes".

At some point I looked up conditional formatting in pandas -- it says [it's still under development](pandas.pydata.org/pandas-docs/stable/style.html), but maybe you can make it work nonetheless.

**Comment by paolorivas** [comment]
This is an awesome idea! I would research for some previous works have been done that would help use as "best practices". Take a look at this!

http://www.theverge.com/2014/10/8/6938041/portland-enlists-big-data-to-make-biking-safer

**Comment by honjy** [comment]
I like this idea. I'm no cyclist, but I wonder how cyclists pick the routes that they do? Besides road width, is the business of a street also a consideration? And if you're creating a chart, is there a way to visually represent number of cyclists versus width so that we understand what you're trying to say immediately?
