### ISSUE TITLE
Analysing Bus Fleet Performance in the City of Hyderabad

### ISSUE THREAD

**Issue by HarshaDevulapalli** [jsoma/playfair-projects#181]
The city of Hyderabad is home to the Road Transport Corporation that until recently held record for the largest fleet owned by a single government entity in the World. 

I have come across Operational Data for the city's bus network that has data on how the different kinds of bus categories have performed in terms of Earnings Per Kilometer, Occupation Ratio and Vehicle Utilization. I will compare them across categories to demonstrate the most value for money bus category. 

The Data is split across four zones : Hyderabad, Charminar, Secunderabad and Sanath Nagar. So I can do a zone vs zone comparison as well as an overall scenario. 

More details to come up soon.

The data is linked [here.](https://drive.google.com/file/d/0B1vcWI83kfIlQVlERDFlLXBWTkswMVFMMWVSOHpKWG1PUzc4/view?usp=sharing) 
# Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [x] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [ ] My pitch issue includes multiple possible headlines
- [ ] My pitch issue includes any links/images I'm using as inspiration
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by gcgruen** [comment]
Is your data geocoded? Maybe that's a good map topic, especially with the "occupation of bus lines"? Maybe there are many bus lines in places with low occupation - that would be a cool narrative.

**Comment by barjacks** [comment]
Hey, looks like an interesting data set you have here? I'm not completely sure what the various columns are. Can you provide the data dictionary as well? I am guessing the Eng Kms is the kilometres the vehicle has covered? You could do lot with this: Work out, which bus is used the most, in which time frame, and, maybe with a bit more digging at the data source, whether the buses than run more are also serviced more frequently.
