### ISSUE TITLE
DJL:  Fast Food Store Distribution in Korea

### ISSUE THREAD

**Issue by djlee0202** [jsoma/playfair-projects#182]
The following is the initial outcome, showing the distribution of the major fast food stores in Korea. 
( After 08/08/2016 Class, I labeled each city/province in the map.)

![distribution of the fastfood_updated](https://cloud.githubusercontent.com/assets/19519829/17489910/5e4cabb4-5d6e-11e6-96a6-95e40fa4866a.png)

## Story issue checklist

My pitch was (use the number): #107

- [x] My pitch has been approved (see `PITCHING.md`)
- [x] My story issue links to my pitch issue
- [x] I have included an update of my visualization/story in a comment
- [x] I have received two comments of peer feedback
- [x] I have received editorial feedback

**Comment by honjy** [comment]
These maps are so pretty! I think the only suggestion I have is that I'd add labels that show where Seoul is, or maybe the other major cities - just to show that Burger King and KFC are all concentrated in Seoul while Lotteria isn't - just because many of us don't know where Seoul is on a map.

**Comment by paolorivas** [comment]
It is difficult to identify that is S.Korea if you are not familiar with the country's shape and provinces. I would suggest to make it more explicit in the graph. Also the legends seem to be too small to recognize the density of this chain food.  Otherwise, I like it!

**Comment by jsoma** [comment]
Guess we did CartoDB at the right time!

You asked in class, and I can tell now: [this is how to export an image from Carto](https://carto.com/docs/carto-editor/maps/#export-image)

**Comment by juneeseo** [comment]
It would be helpful to have a legend. Now it is hard to understand by just looking at those colors. You can make a simple legend at Carto. And I would also like to see the total number of each fast-food restaurant!

**Comment by honjy** [comment]
Love the updates DJ! I think I'd look at making the yellow map more transparent, just cos it looks like there are way more Burger Kings than Lotterias or KFCs.

**Comment by radhikapc** [comment]
Incredible ! I liked the map. It would be nice if you work on the color scheme (in particular, color Yellow). It would also be good if you add legend.
