### ISSUE TITLE
Globalization of higher education: who goes where?

### ISSUE THREAD

**Issue by shuyao1201** [jsoma/playfair-projects#185]
# Summary:

Which country is most popular for international students?  Students in each country prefer to go  where? What's the proportion of foreign students in your country? How about the flow of tertiary-level students in each country?

I am going to make my own version based on UNESCO's datasets.

![qq20160808-1](https://cloud.githubusercontent.com/assets/19495692/17496984/b34be67e-5d8d-11e6-8e01-d0e9af14cee9.jpg)
# Data Source:

UNESCO(United Nations Educational, Scientific and Cultural Organization):
http://data.uis.unesco.org/Index.aspx?DataSetCode=EDULIT_DS&popupcustomise=true&lang=en#

http://www.uis.unesco.org/Education/Pages/international-student-flow-viz.aspx
# Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [ ] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [x] My pitch issue includes multiple possible headlines
- [x] My pitch issue includes any links/images I'm using as inspiration
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by spm2164** [comment]
Pretty cool idea. I'd love to see this as a static map that highlights the biggest student migrations. That would be a pretty big and complicated map, but who knows! I think it'll be great.

**Comment by barjacks** [comment]
I like your first question: Which country is most popular for international students? Could you work this out related by size of the destination country? And could you maybe developed different categories of destinations. This could reveal some interesting results (might not be US).

**Comment by nickyforster** [comment]
With a dataset like this it can be easy to fall into the trap of making a visual/story that is too exploratory, so asking specific questions like you have is definitely the way to go.

	- I would avoid a map in this case. Flow map’s often look impressive but can be very difficult to follow and nearly impossible to quantify. People love [this map by Minard](http://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=00002j) but things become very unwieldy very quickly.

	- I’ve seen a mixed design of Tuftian (maybe that’s a term?) slopegraphs and sankey diagrams to visualize immigration and I think it works pretty well. Another option is to take from what The New York Times [visualized about where Americans move within the country](http://www.nytimes.com/interactive/2014/08/13/upshot/where-people-in-each-state-were-born.html). 

	- A cool takeaway from those New York Times charts might be to focus on the proportion of students that stay in their own country vs those that leave. I don’t think the brain drain phenomenon refers to students being educated away from their home countries but I would imagine many become employed in the countries they studied in. It would be interesting to compare the fortunes of countries that lose a large proportion of their students with those that lose very few/receive many.
