### ISSUE TITLE
[DJL] The Size of Residential Apartments in South Korea Cities [Pitch]

### ISSUE THREAD

**Issue by djlee0202** [jsoma/playfair-projects#19]
The purpose of this analysis is to understand interesting statistical facts regarding  the size of apartments in South Korea Cities. According to the Korean Government, residential properties larger than 900 sq ft are considered "large residential property" for tax purpose. I decide to figure out the number of such large apartments in the data set and its ratio to the entire market.

Large Apartment Ratio  = 
(Number of Large residential properties larger than 914 sq ft )/(Number of Entire Residential Property)

Inspired link : https://www.washingtonpost.com/world/after-decades-of-economic-growth-south-korea-is-the-land-of-apartments/2013/09/15/9bd841f8-1c55-11e3-8685-5021e0c41964_story.html

===============================================

South Korea consists of 10 provinces & 8 metropolitan cities. Most apartments are concentrated in Metro Cities and Kyungi, a Province Area near Seoul. 

![image](https://cloud.githubusercontent.com/assets/19519829/17104943/1480b924-5253-11e6-9fb5-047be3df115b.png)

#####           8 Metropolitan Cities
Seoul (1), Busan (2), Daegu (3), Incheon (4), Gwangju (5), Daejeon (6), Ulsan(7), Saejong(8) 

#####           Suburban province containing majority of Apartments in South Korea:
Kyungi  (A)

**Comment by jsoma** [comment]
Added [Pitch] to title so I can search/label more easily

**Comment by spm2164** [comment]
If I was doing this project, I would be very interested in how much housing is build close to, but below, the threshold that triggers this large additional tax. Also, whether or not people are getting around it by building balconies (which don't count as we discussed), or improved/finished attics, etc.

**Comment by shuyao1201** [comment]
There might be a relationship between population and distribution of large apartment,  if there were more people live in the city, large apartments would be less. That's what I'm curious about.
