### ISSUE TITLE
How accessible is Madrid's subway network?

### ISSUE THREAD

**Issue by oargueso** [jsoma/playfair-projects#20]
Based on data from [Madrid subway's website](https://www.metromadrid.es/es/viaja_en_metro/red_de_metro/estaciones/index.html), my aim is to visualize how easy/difficult it is for people with mobility problems (i.e., people on a wheelchair, elderly people) or other kind of needs (parents carrying their babies in a stroller or travelers with heavy luggage) to make their way through Spain's capital subway network. My inspiration is this map of NYC subway's accesible stations (source: https://subwayrecord.wordpress.com/2015/03/26/the-mtas-accessibility-gap/), which I would like to reproduce for Madrid: 
![subway-wheelchair-map-1433769981](https://cloud.githubusercontent.com/assets/15266954/17105030/7ded0782-5253-11e6-8492-1e8e1fefee7e.jpg)

Since the data are not directly available and scraping Metro de Madrid's website is not possible, I just built the database for the 275 stations manually, including information about the kind of equipment they have (escalators, elevators).

**Comment by mercybenzaquen** [comment]
Awesome idea, I love it. I think the map will be a strong visualization and once you work with the subways of other countries you could use other types of graphs to compare them. You should also hold on to this idea for when we learn to create interactive maps I think it would be pretty cool to be able to hover over different stations and get more info on their accesibility.

**Comment by kbennion** [comment]
This sounds like a really important and interesting project. A comparison of the maps (accessible vs inaccessible) would be very powerful. I don't know much about the Madrid subway system, but are some stations used more than others? If they're bigger or used more often, maybe that could be indicated or weighted more somehow?

**Comment by skkandrach** [comment]
This is a great idea! I think if you can visually convey the accessibility in a chart that would be a great addition to the map so people can compare how the metro assists people with disabilities or parents. Can't wait to see how this shapes up!

**Comment by oargueso** [comment]
Thank you all for your feedback! I find your suggestions really useful.

**Comment by oargueso** [comment]
I have already carried out some analysis on my database. Here are some of **my main findings**:

* Two thirds of the stations (183 or 67%) are adapted for people with disabilities.
* In more than half the stations (157 or 57%) there is an elevator.
* Three in four stations are equipped with escalators (202 or 73%).
* 12% of the stations (34) have neither elevator nor escalators. 11 of these (the highest number) belong to Line 1, the oldest, which is undergoing major construction works this summer. However, as Metro de Madrid press office has explained to me, this repairs do not include revamping the stations. That is, there will be not improvement to make them more easily accessible for people with mobility problems.

Besides, following my fellow students advice, I have looked for data about how many passengers use each line each year. This will allow me to see if the most used are maybe the most/less/average accessible. Here is a link to the data from [Metro de Madrid's website](https://www.metromadrid.es/export/sites/metro/comun/Portal_de_transparencia/Documentos/Informacion_economica/Demanda_2015.pdf).

**Comment by oargueso** [comment]
## Pitch issue checklist

- [ ] My pitch issue has `[Pitch]` in the title
- [ ] My pitch issue has `[Data request]` in the title if I need additional data
- [ ] My pitch issue links to my data set
- [ ] My pitch issue explains what I'd like to explore in the data set
- [ ] My pitch issue includes multiple possible headlines
- [ ] My pitch issue includes appropriate labels in the title such as `[Pitch]` and maybe `[Data Request]`
- [ ] I have received two comments of peer feedback on my pitch issue
- [ ] I have received editorial feedback on my pitch issue
- [ ] My pitch has been approved

**Comment by oargueso** [comment]
I have already received the data I needed from Metro de Madrid's press office.

**Comment by jsoma** [comment]
Story created, closing
