### ISSUE TITLE
[Story 5] Public defender funding in the U.S.

### ISSUE THREAD

**Issue by snajmabadi** [jsoma/playfair-projects#228]
Potential data sources:

http://www.bjs.gov/index.cfm?ty=tp&tid=28
http://ojp.gov/newsroom/factsheets/ojpfs_indigentdefense.html
http://www.bjs.gov/index.cfm?ty=dcdetail&iid=401
http://www.pbs.org/wgbh/pages/frontline/shows/bostonda/etc/stats.html
http://www.motherjones.com/politics/2013/05/public-defenders-gideon-supreme-court-charts

I intend to create an interactive graphic of public defense spending across the United States. If possible, I will try to combine that funding data with information about lawsuits or legislative/policy changes that have taken place in the states as well. I will be focusing, in particular, on change over time, and any differences between states in the source and amount of funding. 

Possible headlines could include: 

"x state pays the most for public defense"
"y state pays the least"
"Most states fund public defense from x fund"
etc. 
# Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [x] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [x] My pitch issue includes multiple possible headlines
- [x] My pitch issue includes any links/images I'm using as inspiration
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by barjacks** [comment]
Great idea. And very ambitious project. There is a lot of data there and a lot of comparisons you can make. Really think you should try to focus on what you'll be comparing as early on as possible.

**Comment by snajmabadi** [comment]
in progress: 

![pd2-1-01](https://cloud.githubusercontent.com/assets/13809417/17857865/6bab84ea-6851-11e6-900a-71177b59741c.png)

**Comment by thisss** [comment]
Good approach. You also have some interesting graphs already. I am looking very much forward to an interactive one. It would be great to able to explore the changes over time.

**Comment by kbennion** [comment]
Wow! What an important project. It might be helpful to compare case per spending ten years ago and now -- combining some of your data on case load and spending, like 2005 budget was $x per case, today it's $x.
