### ISSUE TITLE
Continuation With Frozen Four, Tierney, Phelps and Olympic Athletes that Choked Projects

### ISSUE THREAD

**Issue by skkandrach** [jsoma/playfair-projects#231]
For my Final Project I will be working on finishing/updating my three previous projects since there was so much data and areas to explore within the data. 

Also, I want to add Olympic athletes that were favored to win entering into the competition and then ended up choking (not fulfilling gold expectations). This data is hard because its not necessarily something that exists, but I think if I can go sport by sport for maybe this (2016) Olympics and the (2012) Olympics to compare the progress/regression of teams/individual competitors performances/outcomes, in maybe a scatter plot?

See #178 #106 and #17 
## Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [x] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [ ] My pitch issue includes multiple possible headlines
- [ ] My pitch issue includes appropriate labels in the title such as `[Pitch]` and maybe `[Data Request]`
- [ ] I have received two comments of peer feedback on my pitch issue
- [ ] I have received editorial feedback on my pitch issue
- [ ] My pitch has been approved

**Comment by oargueso** [comment]
It seems quite a project! Regarding the story about Phelps, I saw this today on the FT, you may find it useful:

![pasted image at 2016_08_15 10_00 am](https://cloud.githubusercontent.com/assets/15266954/17674579/2554bf1e-62f4-11e6-9760-847fc7578d10.png)

Looking forward to seeing those graphs :)

Good luck!

**Comment by mercybenzaquen** [comment]
Yeyyy more sports! I think it is smart to continue to work on these projects, you have tons of cleaned and manageable data now after hard work! I just read Kate's pitch and sent her this link https://www.washingtonpost.com/graphics/sports/olympics/olympics-collection/. They have tons of visualizations for sports (olympics) but I think you can get some ideas from there.
