### ISSUE TITLE
Rio 2016 Athletes by Country

### ISSUE THREAD

**Issue by kbennion** [jsoma/playfair-projects#232]
I'd like to do another project with my Rio athlete data. I am thinking number of athletes represented by country: some kind of bar graph visualization with flags. Sounds cheesy I know, but I think I could do some interesting things with placement. So the size of the flag will be proportional to how many athletes are competing in the Olympics for that country. I'll have to watch width and make sure the flag remains proportional while not being deceptive with actual size.

Possible headlines:
Best-represented countries of the Olympic games
U.S., China have a TON of Olympians
Most underrepresented populations at the Olympics
# Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [x] My pitch issue has `[Data request]` in the title if I need additional data
- [ ] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [x] My pitch issue includes multiple possible headlines
- [x] My pitch issue includes any links/images I'm using as inspiration
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by mercybenzaquen** [comment]
I love the Olympics idea so it is great you are continuing to work with it :).  Interesting angle, I am curious to see which are the most underrepresented populations at the Olympics. It would be cool to also see how many medals these countries take home compared to their number of athletes. 
I just did a quick google search to see if I could find some inspiring images for you and found this really cool charts by, of course, the NYT. 
http://www.nytimes.com/interactive/2016/08/08/sports/olympics/history-olympic-dominance-charts.html?_r=0

**Comment by mercybenzaquen** [comment]
Also, look check this out, they have tons of vizs here! https://www.washingtonpost.com/graphics/sports/olympics/olympics-collection/

**Comment by gcgruen** [comment]
What a cool project! It's great to know that you successfully built a scraper so now we know who to ask in case of questions. 
Also your visual ideas sound great -- I like the idea of integrating the flags of each country (bc: who knows the flags really? And it's a bit more exciting than just bars). Also, if you investigate age distribution, maybe that would be a cool small multiple to see which is the oldest sports or which has the widest age range (along the lines of: if you are too old for sports a, just do sports b!)

**Comment by kromreig** [comment]
Good luck on your scraper! I think there are lots of really exciting possibilities for visualization here. I agree that small multiples would be really cool. Maybe think of what is the *story* you're interested in telling, because I think a challenge you're going to have is what to focus on with so much data. Small multiples by sport, by country, or by age, would be very cool. What sport is the most diverse by age or country? What country practices the most different sports, the least different sports?
