### ISSUE TITLE
New York State School Demographics

### ISSUE THREAD

**Issue by M0nica** [jsoma/playfair-projects#238]
I would like to further explore NYC/NYS school data to look at racial demographic and median income.

Eventually, I would like to combine with my other school district data (https://github.com/jsoma/playfair-projects/issues/183) and see if a correlation can be made b/w racial demographic, median income and amount of money spent per student.  

Pitch issue checklist
- [ ]  My pitch issue has [Pitch] in the title
- [ ]  My pitch issue has [Data request] in the title if I need additional data
- [ ] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [ ]  My pitch issue includes multiple possible headlines
- [ ]  My pitch issue includes any links/images I'm using as inspiration
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by oargueso** [comment]
Very interesting project, indeed. I think it is really amazing that the difference between schools is so huge in terms of the money they spend per student. It definitely deserves digging into it to find the possible causes behind those differences.

**Comment by mercybenzaquen** [comment]
This is an interesting project! I think you could actually make this one your big project and create separate charts for the different correlations that you have in mind. I think this would work as a D3 project and you could make it as a map with an option of choosing the parameter you want to look at. For example median income, race demographics, etc.

**Comment by M0nica** [comment]
Demographic Snapshot Data Source http://schools.nyc.gov/Accountability/data/default.htm

**Comment by M0nica** [comment]
![screen shot 2016-08-22 at 10 29 14 pm](https://cloud.githubusercontent.com/assets/6998954/17878352/236a4c22-68b8-11e6-8b47-bef4598a5f0a.png)

Created a D3 visualization of demographic break-down of NYC school districts. I need to figure out how to add X and Y axis labels to this graphic. Currently, I am using raw numbers as opposed to percentages. Is it weird to graph percentages with a bar chart?

**Comment by M0nica** [comment]
From the same data source, I also have #s for Poverty, English Language Learners and Students with Disabilities. 

Maybe I could have multiple buttons: Display Racial Demographic, Gender Breakdown, Poverty Level, # of English Language Learners and # of Students with Disabilities. Still not sure if raw numbers of percentage is better for displaying this type of information.

**Comment by mercybenzaquen** [comment]
These look great! As we were discussing, I think it would be very interesting to see the school districts on a map as well. I like your idea of having a map below the bar chart and highlighting the corresponding bar as the viewer hovers over the district on the map. I like the colors, they look cool!

**Comment by M0nica** [comment]
[NYC Acronym Reference] http://schools.nyc.gov/NR/rdonlyres/0C56D9B8-8DDB-46B8-AA5F-BF77AE8C2803/0/ACRONYMReferenceGuide.pdf

NYC School Districts are 1-31, 75, 79 and 84. I would like to represent each district separately, as well as comparing 1-31 (regular public school districts), 75 (special education), 79 (alternative high schools) and 84 (charter schools) to each other. 
>

-  District 75 Special Education: District 75 provides citywide educational, vocational and behavior support programs for students who are on the autism spectrum,  severely emotionally challenged, and/or multiply disabled. Learn more here.

- District 79 Alternative Schools and Programs: Helps students under 21 years
old, who have experienced an interruption to their studies to stay on track to a high
school or high school equivalency diploma, build the skills to succeed in postsecondary
opportunities, and gain the social-emotional skills necessary to become
confident and productive members of society. Learn more here.

- District 84 Charter Schools: Publicly funded and open to all students in New York
City through a non-discriminatory admissions lottery. Each charter school is
governed by a not-for-profit board of trustees which may include educators,
community members, and leaders from the private sector. Learn more here.

**Comment by kbennion** [comment]
I love these visuals -- I liked what you talked about about incorporating a map somehow so people could easily identify what district the data is for (a map on the side that highlighted what district the mouse was over would be so cool). I'm not sure the best way to transition between different data sets as you mentioned. It might also be worth seeing how it looks when you order the districts in numeric order so people who are looking for their district specifically can find that information?

For the first graphic, I might change the color for "Black" so it looks less like a gradient scale between "Hispanic" and "Asian."

**Comment by M0nica** [comment]
![screen shot 2016-08-24 at 3 15 54 pm](https://cloud.githubusercontent.com/assets/6998954/17944458/cda5d4a8-6a0d-11e6-80ee-a179028a5dba.png)

Grouped by type of school in order to tell a more cohesive story.

**Comment by M0nica** [comment]
![screencapture-localhost-8000-index-stacked-html-1472153417896](https://cloud.githubusercontent.com/assets/6998954/17983107/f01f6fd2-6ad8-11e6-931b-503567d32f0c.png)

Updated with information about private school enrollment, contrasting colors and brief write up.

**Comment by M0nica** [comment]
D3 Visualization can be viewed live on my website, here: http://aboutmonica.com/nyc_school_demographics/
