### ISSUE TITLE
Dataviz series on water

### ISSUE THREAD

**Issue by gcgruen** [jsoma/playfair-projects#244]
I would like to dive into some water data -- there's such a variety!
Usually we take water for granted, though we somehow know in the back of our minds that it is not. With these visuals I would like to draw attention to _how scarce_ it actually is.
# Visuals

Inspired by @kromreig playing with this idea, I would like to do a slope graph on annual freshwater withdrawl:
![fullsizerender 4](https://cloud.githubusercontent.com/assets/7279358/17832046/1b9b58ac-66c8-11e6-95ec-10cac7f9e7f4.jpg)

Also, I would like to find a way to like visualize the correlation between water scarcity and conflict. Either by a spider-web-thing (which I would like to try for some project) or by something similar @HarshaDevulapalli did for his GDP-military coup story:
![fullsizerender 3](https://cloud.githubusercontent.com/assets/7279358/17832040/fa2cb2d8-66c7-11e6-93f6-3be0492e12c7.jpg)

Third visual will be a map -- either of water scarcity prediction or drought. But that would be just replicating what is there (advantange: I know it is feasible) and that's a bit (disadvantage) boring. So I thought, maybe I could focus on rivers -- cluster them based on baseline water stress predictions and map them in a specific colour for each cluster.

More topics to explore visually, based on available data:
- national water footprints
- product water footprints
- water pollution
- water & sanitation
# Data

[Freshwater](http://data.worldbank.org/indicator/ER.H2O.FWDM.ZS)
[Conflicts linked to water -- needs scraping, which I wanted to do for a project anyway](http://www2.worldwater.org/conflict/list/)
[Data on water and sanitation](http://www.ib-net.org/)
[Water and conflict -- overview](http://pacinst.org/issues/water-and-conflict/)
[Geospatial data -- many indicators](http://www.wri.org/resources/data-sets/aqueduct-global-maps-21-data)
[Geospatial data -- water stress prediction](http://www.wri.org/resources/data-sets/aqueduct-water-stress-projections-data)
[Geospatial data -- river basin indicators](http://www.wri.org/resources/data-sets/aqueduct-country-and-river-basin-rankings)
[Water footprint and water pollution](http://waterfootprint.org/en/resources/water-footprint-statistics/)
[Water and drought](http://www.iwmi.cgiar.org/resources/tools-and-resources/)
# Clip search/ primary sources

[Pacific Institute: Peak water](http://pacinst.org/issues/sustainable-water-management-local-to-global/peak-water/)
[WRI: Water](http://www.wri.org/our-work/topics/water)
[Cool thing: Live updating counter how much water has been consumed this year](http://www.worldometers.info/water/)
[World Bank - Feature on Water](http://www.worldbank.org/en/topic/water)
[FAO resources on Water](http://www.fao.org/nr/water/aquastat/main/index.stm)
[Water Management](http://waterdata.iwmi.org/)
[Global Water Resource Collection](http://www.globalwaterforum.org/resources/data/)
# Possible headlines
- Water stress causes conflict
- Product x has the highest water footprint
- Country z is depleting its freshwater resources
# Pitch Checklist
- [x] My pitch issue has `[Pitch]` in the title
- [x] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [x] My pitch issue includes multiple possible headlines
- [x] My pitch issue includes any links/images I'm using as inspiration
- [x] I have received two comments of peer feedback on my pitch issue

**Comment by mercye** [comment]
there are so many entry points for this, and i am super excited to see which direction you will go with this.  i think it would be super interesting to look at what level of water scarcity a conflict breaks out/if water scarcity can predict conflicts.

**Comment by kromreig** [comment]
So, I reserve making much comment until I see what data you're going to use and what you decide to visualize :)

I think that this is a big topic, and that focusing on specific topics might work really well. Maybe that means you pick a specific region, a specific time range, or a specific context (during/before/after a conflict, for instance).

So yeah! Go for it! Exciting!
