### ISSUE TITLE
Price of clothing decline while everything else rises

### ISSUE THREAD

**Issue by mercye** [jsoma/playfair-projects#248]
## inspiration

[Dress for Less and Less](http://www.nytimes.com/2008/05/29/fashion/29PRICE.html?_r=0) 

The article talks about how the cost of mainstream clothing has been in decline, while luxury clothing has perhaps reached it apex. 

I want to look at those numbers over time, and see where the decline started. What the circumstance were, etc. 
## data

[Bureau of Labor Statistics](http://www.bls.gov/data/#api)
## potential headlines

Everything's gotten more expensive, excepts clothes. 
Why has the clothing of price declined while everything else's gone up?
# Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [ ] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [x] My pitch issue includes multiple possible headlines
- [x] My pitch issue includes any links/images I'm using as inspiration
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by gcgruen** [comment]
Wow, such a cool project and so intruiging! I think your audience will love it and you should definitely try to sell it to some media outlet - they'll love it!

I'm really curious what correlations you find, like for example economic events (maybe global expansions or founding of new major clothes branches). In terms of what products to compare it to, I think what Harsha suggested is important: To think of what is similar essential as clothes. 

Really exciting project!

**Comment by kromreig** [comment]
Sorry for taking so long to comment!

I think this is super super interesting! I would be interested to know why this industry has passed along savings to the consumer, while many industries have not...

Perhaps compare the price decline with garment manufacturing wages over time? That may be complicated, though, with different countries and currencies.

Excited to see what you come up with :)
