### ISSUE TITLE
Public toilets rating

### ISSUE THREAD

**Issue by palrogg** [jsoma/playfair-projects#253]
I'd like to let people rate public toilets in Geneva.

[link](http://www.ville-geneve.ch/themes/environnement-urbain-espaces-verts/publics/)

I'm not sure which solution to use yet: maybe leaflet + SQL server or a third party service.
# Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [x] My pitch issue has `[Data request]` in the title if I need additional data
- [ ] My pitch issue links to my data set
- [ ] My pitch issue explains what I'd like to explore in the data set
- [ ] My pitch issue includes multiple possible headlines
- [ ] My pitch issue includes any links/images I'm using as inspiration
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by gcgruen** [comment]
Haha, that's a cool project!!! And so easily scalable! I hope it brings you lots of calls with requests to replicate it for different cities.

Maybe you could also think about whether there's another dataset this could be combined with -- is there something that could correlate with dirty public toilets?
