### ISSUE TITLE
Are Spanish female athletes honoring better the public funds they receive?

### ISSUE THREAD

**Issue by oargueso** [jsoma/playfair-projects#258]
# Story issue checklist

My pitch was #218 

- [x] My pitch has been approved (see `PITCHING.md`)
- [x] My story issue links to my pitch issue
- [x] I link to my finalized (ish) data source(s)
- [x] I've included a brief summary of my story
- [x] I've included some possible headlines or findings
- [ ] I've included some links or images as inspiration (if you have any)
- [x] I have received two comments of peer feedback
- [x] I've included an update of my visualization/story in a comment
- [ ] I have received two comments of peer feedback after posting an update
- [ ] I have received editorial feedback

After scraping the data from [this page](http://www.ado.es/becados/listado/), I now have a nice database with all the information for the 171 Spanish athletes that are receiving public funds and their results for the Olympic Games, World Championships and European Championships. 

My main headlines, so far:

- Female athletes have won over 200 medals between 2003 and 2016, while their male peers have only won over 100. 

- Regarding the quality of these medals, men and women have won almost the same number of gold medals (53 for men, 51 for women, although there are fewer women), but female athletes beat men in silver and bronze, where they have won almost twice as medals. 

And here is a first viz (nothing very flashy and definitively not interactive!):

![medallas_total](https://cloud.githubusercontent.com/assets/15266954/17933642/e32d4ed0-69e2-11e6-947b-4dba93993f25.png)

Note: I forgot to add the source of the medal icon: Thomas Hirter from the Noun Project. I will add it in my review of this chart.

I would like to go deeper in my analysis, looking for more insights, like the ratio of medals per gender, an evolution of the number of medals per gender and type of competition, who is the best athlete per gender, maybe also a breakdown per sport... Work in progress!!

**Comment by kbennion** [comment]
I really like your minimalist graph here, especially the medals. Good color choice too -- the purple is subtly feminine. I think it would be good to indicate somewhere on the graph where the medals are from (I didn't know other competitions besides the Olympics issued gold/silver/bronze medals...). There are so few bars that you could just indicate the number of medals at the top of each bar instead of having the y-axis label way on the side; I think that would be easier to read and tell the story.

**Comment by mercybenzaquen** [comment]
Bravo Olaya! This was exteeeensive scrapping and I am glad you were able to get all the information you needed. Two suggestions that I just noticed and think could improve your chart:
-Try another font, I am not sure totally sure about the one you are using now (for the legend and axis).
-The difference between gold medals is hard to see. You mentiones that you might put the numbers on top of your bars and get rid of your y axis. I think that would work.
:)

**Comment by oargueso** [comment]
Here is the update of my visualization:

(Although one of the bars seems to be missing, it is a format problem: it disappeared when converting my .svg file into a .png. But I swear it is there!)

![medallas-ado](https://cloud.githubusercontent.com/assets/15266954/17949116/f19ee692-6a21-11e6-94ba-616ee9c79e2c.png)

The text explains how female athletes receiving public funding have won 60% more medals than male athletes in the same state-backed program in all the international competitions they have taken part in since 2003. 

Both genders are pretty close in gold medals, women have brought home a higher number of silver and bronze medals (around twice as many), as shown in the top left chart.

I now would like to analyze each sport (are women better in track and field, for instance?) and each year. 

Women seem to do better in the Olympic Games (bottom left chart) and the European Championships (bottom right). Men, in turn, do better in World Championships (top right).

**Comment by oargueso** [comment]
Although very late, here is my updated (and final) viz for a project that has taken longer than expected:

![medallas-ado](https://cloud.githubusercontent.com/assets/15266954/18150062/3f2b9906-6fb2-11e6-8b81-4e8aac65a26b.png)
