### ISSUE TITLE
Rents Increase VS. Airbnb in NYC

### ISSUE THREAD

**Issue by shuyao1201** [jsoma/playfair-projects#26]
I was inspired by this interactive reports, mapping the relationship between the rents rise in Berlin and Airbnb bussiness expansion: http://www.airbnbvsberlin.de/

I want to do the same about New York City. It might include: the number of Airbnb listings in NYC, the distribution of prizes of the NYC Airbnb offers, the top 10 providers of Airbnb,top 10 streets and the number of apartments rental advertisements......

I will begin with graphing the Airbnb data, then the rents changes, then try to find a relationship between them. 

Here is the data I may use:
rents data from streeteasy.com or zillow.com or .......
airbnb: http://insideairbnb.com/new-york-city/
http://insideairbnb.com/get-the-data.html

Datasets I have:
![image](https://cloud.githubusercontent.com/assets/19495692/17166478/25886002-53a5-11e6-90bc-4d5278dbf0d4.png)

**Comment by shuyao1201** [comment]
My pitch was : #26

- [ ] My pitch has been approved (see `PITCHING.md`)
- [ ] My story issue links to my pitch issue
- [ ] I have included an update of my visualization/story in a comment
- [ ] I have received two comments of peer feedback
- [ ] I have received editorial feedback

**Comment by shuyao1201** [comment]
![image](https://cloud.githubusercontent.com/assets/19495692/17282973/89ef4ede-5779-11e6-883d-82bb8252791e.png)

**Comment by jsoma** [comment]
Story completed, pull request merged
