### ISSUE TITLE
MTA debt & fares

### ISSUE THREAD

**Issue by mercye** [jsoma/playfair-projects#260]
**Pitch number:** #186 

**Data sources** 
[MTA outstanding debts](http://web.mta.info/mta/investor/pdf/2016/debt_outstanding.pdf)
[Historical Inflation Rate](http://www.usinflationcalculator.com/inflation/historical-inflation-rates/)
[NY Dept of Labor](https://www.labor.ny.gov/stats/minimum_wage.asp)
[MTA fare](http://mashable.com/2015/03/22/new-york-city-subway-fare/#lultF98LTPqh)

**Summary**
Looking at the relationship between mta debts, the rise in minimum wage, and the price of transit 

**Data Requests**
-- if i can find data, i would like to add info about the increase in fines/summonses. 

**Possible Headlines**
still, working here...

**Images**
![inf_minwage_30day_norm](https://cloud.githubusercontent.com/assets/7256760/17944771/1abab582-6a0f-11e6-847f-ec153405a427.png)
![inf_minwage_singleride_norm](https://cloud.githubusercontent.com/assets/7256760/17944775/1abfada8-6a0f-11e6-93df-69e69cbf5345.png)
![minwage_30day](https://cloud.githubusercontent.com/assets/7256760/17944776/1ac16c4c-6a0f-11e6-9e38-b9c7b69d67c4.png)
![minwage_singlefare](https://cloud.githubusercontent.com/assets/7256760/17944774/1abf12f8-6a0f-11e6-90e0-2342415bc74a.png)
![minwage-single-ride-two-axes_pctch](https://cloud.githubusercontent.com/assets/7256760/17944772/1abe0fde-6a0f-11e6-9aae-2efb721eccdd.png)
![minwage-single-ride-two-axes](https://cloud.githubusercontent.com/assets/7256760/17944773/1abf20fe-6a0f-11e6-9fb8-6cd28799213e.png)
![mtadebt_30day](https://cloud.githubusercontent.com/assets/7256760/17944780/1ac5e7c2-6a0f-11e6-94a5-27f70dcadfe2.png)
![singlefare_pct_minwage](https://cloud.githubusercontent.com/assets/7256760/17944778/1ac581f6-6a0f-11e6-8d13-4d05e49fc719.png)
![thirty-day-debt-two-axes_pctch](https://cloud.githubusercontent.com/assets/7256760/17944781/1ac971e4-6a0f-11e6-9993-cd3898a4d0f8.png)
![thirty-day-debt-two-axes](https://cloud.githubusercontent.com/assets/7256760/17944777/1ac4964c-6a0f-11e6-9e5d-54d683ad7bde.png)
# Story issue checklist

My pitch was (use the number): _
- [ ] My pitch has been approved (see `PITCHING.md`)
- [x] My story issue links to my pitch issue
- [x] I link to my finalized (ish) data source(s)
- [x] I've included a brief summary of my story
- [ ] I've included some possible headlines or findings
- [x] I've included some links or images as inspiration (if you have any)
- [x] I have received two comments of peer feedback
- [x] I've included an update of my visualization/story in a comment
- [ ] I have received two comments of peer feedback after posting an update
- [ ] I have received editorial feedback

**Comment by barjacks** [comment]
Really great idea, to map this out. You have so many graphs, I find it a little overwhelming at first. Spending a little time with them, I find the two charts "Single Ride Fair as percentage of minimum wage", "30 days pass and MTA debt" the most interesting. There clearly seems to be a relation between price rises and the MTA debt. (Is there? Why?) And you clearly show that fairs are rising for people around the minimum wage bracket. I would definitely start you story off with this chart.

**Comment by gcgruen** [comment]
Wow, so many line graphs! I like the scope of this topic, because I think it is very accessible for users as they can easily relate to it (similar as with your clothes project!).

I would kind of agree with Barney though that it is a bit overwhelming. Maybe choose two graphics with the strongest story? Or maybe having explicit headlines with each also helps.

I think it's an important thing to take inflation into account, however I was thinking whether there's a way to calculate the fares normalized by inflation (especially since fares and inflation at least look unrelated), so that you don't need to plot it separately (and thereby reduce complexity a little bit?).

**Comment by mercye** [comment]
@barjacks @gcgruen i too am overwhelmed! lol. i made a lot of these just to see where the most interesting relationship happened. Thank you for pointing out which graphs seemed most important to you -- that really helps me zoom in on what the "story" is.  also, all of the numbers are adjusted for inflation already, so maybe i don't need to show inflation at all in the graphs?
