### ISSUE TITLE
% Women in Spain's government (1977-2015)

### ISSUE THREAD

**Issue by oargueso** [jsoma/playfair-projects#27]
This graph shows the evolution of the presence of women in Spain's governments since democracy was restored.

**Comment by oargueso** [comment]
[women-government-final.pdf](https://github.com/jsoma/playfair-projects/files/381889/women-government-final.pdf)

**Comment by kbennion** [comment]
I love the historical tidbits -- a little more precision in when exactly they indicate I think would be helpful. I also love your color choice for the line -- female without being pink.

**Comment by mercybenzaquen** [comment]
I loved it! We had a great discussion about it. I think Kate's suggestion of using color to point to the other info in the graph (males) was great. AWESOME!

**Comment by oargueso** [comment]
Thanks for your feedback! I will use Kate's suggestion, I think it will make it more powerful visually.

**Comment by oargueso** [comment]
This is my polished viz, after your feedback.

![women-government](https://cloud.githubusercontent.com/assets/15266954/17116282/0ed07eb0-5285-11e6-9317-b1458f056608.gif)

**Comment by jsoma** [comment]
I LOVE THE CHANGES. I really enjoy the background color and the purple. It's awesome! I'm brain-dumping below, so feel free to ignore what you'd like to.

**AXES:** I'd push down the tick marks to go below the line (there's a tick_params option for that, i think, but you're already most of the way there), and get rid of the minor ticks, as I think there's probably enough going on here. I'd also keep the numbers only on one side... maybe the right, which is an odd choice normally, but it's where all the action is!

**TEXT:** For the title, I'd increase the size of your artboard on the top side and push it up more. Giving things space increases their stature in the visual hierarchy 👍 

**LINES:** For the part on the right-hand side with the gender balance, you probably want to push the vertical line to intercept the curved line below it so they act as one unit. If I knew how to make the curly brace thing I'd be sure to tell you :wink:

How often do governments change? If it's not very often, you could zebra-stripe horizontally - every other government gets a grey background.  So you could see, oh this government came in and suddenly there were more women. It's a good amount of manual work though, and who knows how it would look!

**LABELS:** You could also get rid of some of the labels - you have labels for 0, 10, 20, 30, 40, but if you deleted the labels for 0 and 20 you'd still have the lines to help guide you but not the busy-ness of the numbers.

**ANNOTATIONS:** There's a lot of text in there and I really enjoy reading it, but I'm trying to imagine how to position it better. It might be a case of splitting the information between the visual and the story - "SOLEDAD BERCERRIL: FEW WOMEN", "JOSÉ MARÍA AZNAR: INCREASING WOMEN", "JOSÉ LUIS RODRÍGUEZ ZAPATERO: GENDER BALANCE", "CURRENTLY: FEWER WOMEN" on the chart, and then a deeper explanation on the sidebar (like the insane sports thing from the NYT we saw today in the critiques sheet - it split off deeper explanations to the right-hand side). **Actually** now that I think about it you might want to pull the lines arrows down _beow_ the graphic and then you'll have plenty of space _and_ they'll all be able to line up.

![image](https://cloud.githubusercontent.com/assets/95126/17190734/ef5586a2-5414-11e6-88be-1f0a36f9b389.png)

(Except of course not weird and ugly)

**Comment by jsoma** [comment]
You'll want to add the story checklist in here as a comment - you're all the way there in terms of review, just need to be able to check those boxes!

**Comment by oargueso** [comment]
# Story issue checklist

My pitch was (use the number): _

- [ ] My pitch has been approved (see `PITCHING.md`)
- [ ] My story issue links to my pitch issue
- [ ] I link to my finalized (ish) data source(s)
- [ ] I've included a brief summary of my story
- [ ] I've included some possible headlines or findings
- [ ] I've included some links or images as inspiration (if you have any)
- [ ] I have received two comments of peer feedback
- [ ] I've included an update of my visualization/story in a comment
- [ ] I have received two comments of peer feedback after posting an update
- [ ] I have received editorial feedback

**Comment by oargueso** [comment]
![women-government](https://cloud.githubusercontent.com/assets/15266954/17302141/d27cbdc0-57e8-11e6-8f41-68c0200a261d.png)

**Comment by Bisaha** [comment]
Merged in pull request #74
