### ISSUE TITLE
Energy transition in Europe [Pitch]

### ISSUE THREAD

**Issue by gcgruen** [jsoma/playfair-projects#6]
Germany is hyped for its energy transition: the aim to meet 80% of its energy demand with renewables and cut primary energy demand by 50%, both by 2050.
Moreover, by 2022 the government wants to abandon nuclear energy. Countries like Japan, the US and Britain look at Germany's progress and there's the general perception of 'If the Germans can make it, we can, too!'

However if you look at other European countries, Germany is not leading the *Top10 in Renewable Energy* , but countries like Norway and Sweden are doing way better. Already now the exceed by far the goal the EU set: 20% of energy consumption from renewables by 2020 and use 80% and 50% renewable energy, respectively. Why  aren't they the role models?

Idea for graphic series: Shed light on how European countries compare on renewable energy production and to see whether Germany is or is not a good role model

Background: This goes well with my actual work -- the magazine I work for will have energy transition as the next edition's issue. As the editorial team, we figured we know vaguely about how Germany compares to others, but not in detail, which is why we planned on digging into it.

#### Questions:
* What is each countries total energy demand? (total)

* What is household energy consumption? (per capita + share of total)

* How do countries compare in renewables vs non-renewables as energy source?
[two sided bar graph]

* How has usage of renewables changed over time? (compare 2000 and latest data)
[slope graph]

* How has the energy price changed over time?

* How does energy production distribute over energy sources?
[multiples?]

* Does energy demand relate to GDP and use of renewable energy? (maybe include non-EU-countries)
[scatterplot, x = GDP, y = energy demand, bubble size = share of renewable energy in energy mix]

* How does energy production/use relate to subsidies? (select 5-10 interesting countries based on previous analysis)
[colored scatterplot, one color per energy source, one markertype per country]

#### Headlines:
* For a role model on renewables, look at Norway, not Germany
* The difference that you NOT make -- why saving energy per household doesn't matter
* *third headline yet to be found...*

#### Data Sources:
* [EU data -- renewable shares](http://ec.europa.eu/eurostat/statistics-explained/index.php/Renewable_energy_statistics)

* [EU data -- energy consumption](http://ec.europa.eu/eurostat/statistics-explained/index.php/Consumption_of_energy)

* [EU data -- fossil + nuclear -- EU total](http://ec.europa.eu/eurostat/statistics-explained/index.php/Electricity_production,_consumption_and_market_overview)

* [EU data -- fossil + nuclear -- EU by country](http://ec.europa.eu/eurostat/statistics-explained/index.php/Energy_production_and_imports)

* [EU data -- subsidies](https://ec.europa.eu/energy/sites/ener/files/documents/ECOFYS%202014%20Subsidies%20and%20costs%20of%20EU%20energy_11_Nov.pdf)
[Annex2](http://ec.europa.eu/energy/sites/ener/files/documents/DESNL14583%20Final%20report%20annexes%201-3%2011%20Nov.pdf)
[Annex4](http://ec.europa.eu/energy/sites/ener/files/documents/DESNL14583%20Final%20report%20annexes%204%205%20v3.pdf)

* [EU data -- energy price](http://ec.europa.eu/eurostat/statistics-explained/index.php/Energy_price_statistics)

* [EU data -- comparison to world](http://ec.europa.eu/eurostat/statistics-explained/index.php/The_EU_in_the_world_-_energy)

* [Energy by country](http://ec.europa.eu/energy/en/data-analysis/country)

* [International Data -- pick three for comparison?](https://data.oecd.org/energy/renewable-energy.htm)

#### Further links:
* [Renewables 2050: Global Status Report](http://www.ren21.net/wp-content/uploads/2015/07/REN12-GSR2015_Onlinebook_low1.pdf)

* [Subsidies and cost of EU energy, p.8](https://ec.europa.eu/energy/sites/ener/files/documents/ECOFYS%202014%20Subsidies%20and%20costs%20of%20EU%20energy_11_Nov.pdf)

* [Energy taxation and subsidies in the EU and Norway](http://www.nera.com/content/dam/nera/publications/archive2/PUB_OGP_0514.pdf)

* [Carbon Brief: Europe's progress on renewable energy in five charts](https://www.carbonbrief.org/five-charts-showing-the-eus-surprising-progress-on-renewable-energy)

* [Carbon Brief: Five weird things about the cost of energy study](https://www.carbonbrief.org/five-weird-things-about-the-eus-cost-of-energy-study)

#### Remarks:
* I find it difficult to come up with headline suggestions, without having analyzed the data

## Pitch issue checklist

- [x] My pitch issue has `[Pitch]` in the title
- [x] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [x] My pitch issue includes multiple possible headlines
- [x] My pitch issue includes appropriate labels in the title such as `[Pitch]` and maybe `[Data Request]`
- [x] I have received two comments of peer feedback on my pitch issue
- [x] I have received editorial feedback on my pitch issue
- [x] My pitch has been approved

**Comment by kromreig** [comment]
My feedback: divide and conquer to explore this issue more deeply! Seems like a rather large undertaking and I think it could be more accessible if you divided into smaller chunks to work on.

**Comment by gcgruen** [comment]
## Current status

### Focus on fewer questions:
- renewable vs non-renewable (absolute? share! -- two sided bar graph)
- renewable use related to price? (scatter? two lines?)
- (GDP or population) linked to energy consumption linked to (renewable or renewable subsidies)? (scatter w/ varying bubble size)

### Things that were unexpectedly time consuming:
- use consumption or production data?

### Process:
Started off with first question, looking at who consumes most renewable energy in total -- Germany is the biggest absolute consumer of renewable energy.

![renewable_consumption-by-country-webex](https://cloud.githubusercontent.com/assets/7279358/17175746/470db114-53d7-11e6-8c5b-a71ae62ad894.png)

However if you look at the share of renewable energy in total energy consumed you have a very different picture (also, bc labelling doesn't work anymore...)

![share_renewables-webex](https://cloud.githubusercontent.com/assets/7279358/17175644/a8cefaee-53d6-11e6-80b0-23f7b62f8e0e.png)

###: Intend of further analysis:
Show why Germany is nonetheless a good energy-transition-role-model or carve out which country would be a better role model instead 

### Unsolved problems:
- matplotlib label problem
- matplotlib how to make a two sided bar graph (at some point in future, when all data is there nice and clean...)

**Comment by gcgruen** [comment]
## Pitch issue checklist

- [ ] My pitch issue has `[Pitch]` in the title
- [ ] My pitch issue has `[Data request]` in the title if I need additional data
- [ ] My pitch issue links to my data set
- [ ] My pitch issue explains what I'd like to explore in the data set
- [ ] My pitch issue includes multiple possible headlines
- [ ] My pitch issue includes appropriate labels in the title such as `[Pitch]` and maybe `[Data Request]`
- [ ] I have received two comments of peer feedback on my pitch issue
- [ ] I have received editorial feedback on my pitch issue
- [ ] My pitch has been approved

**Comment by spm2164** [comment]
If you would like to get further into Norway and Sweden vs Germany with the question "why is Germany the model" in mind, you could try comparing just those three, or perhaps just Norway vs Germany. Is there something, beyond raw demand, that Germany is doing that Norway is not? Perhaps their mix of renewable sources is better in the long term, or perhaps their level of infrastructure investment is. Also, I imagine Germany's total power demand is quite a bit more than the Scandinavian countries. Maybe plot over time the percentage of renewable energy over time? It is possible Germany is coming up much faster. Or, none of those things are true and your initial idea that Norway or Sweden should be the model is true.

**Comment by gcgruen** [comment]
Thanks for taking the time to comment! Will take all of that into account!
