### ISSUE TITLE
Week 2: Which Indian City Offers Lucrative Jobs for Technical Writers ? [Help - Map Gen]

### ISSUE THREAD

**Issue by radhikapc** [jsoma/playfair-projects#78]
Technical Writing profession in India is almost as lucrative as Software Development. But which city is the most lucrative city and how about the quality of life ? I have gathered the data from the Society of Technical Communication (STC) India chapter to analyze the salary growth of Technical Writers over years. I am investigating on the quality of life in those cities where you find plenty of Technical Writing job.

![capture](https://cloud.githubusercontent.com/assets/3285001/17353002/89fecf30-5909-11e6-98a9-05f89a3c46a2.JPG)

### Story Issue Checklist

My pitch was (use the number): #78
( 7/30/16 I am toying around with the idea of changing my pitch ! :-) )

- [ ] My pitch has been approved (see `PITCHING.md`)
- [ ] My story issue links to my pitch issue
- [ ] I link to my finalized (ish) data source(s)
- [ ] I've included a brief summary of my story
- [ ] I've included some possible headlines or findings
- [ ] I've included some links or images as inspiration (if you have any)
- [ ] I have received two comments of peer feedback
- [ ] I have received editorial feedback

**Comment by djlee0202** [comment]
I believe the question is vague. Instead of finding lucrative characteristics, I would recommend to narrow it down the topic.

**Comment by honjy** [comment]
We talked about how you'd calculate quality of life using the cost of transport and real estate, and I think that's a little too complex for a one week project. I'd just use Big Mac or the cost of something innocuous like a loaf of bread to measure cost of living. Like in X city your salary can buy you 1,000 loaves of bread, but in Y city even though you earn more you can only buy 800 loaves of bread.

**Comment by djlee0202** [comment]
I agree with Hon. The question is aiming lots of analysis as well as defining job, which might be too much for the salary dataset. (You might need to gather more.) Instead of finding lucrative characteristics,  narrow down the topic, simply focused on the salary. As we discussed, Sometimes, simplicity is the virtue.

**Comment by jsoma** [comment]
I agree with @djlee0202, narrowing it down to salary is great first stepping stone. If it works out well, you could always grow from there.

**Comment by radhikapc** [comment]
I am thinking of comparing the technical writing salary with that of developers, and I have dataset from 2005 to 2015 for technical writing from Society for Technical Writers, and now in search of data on dev salary.

**Comment by radhikapc** [comment]
![download](https://cloud.githubusercontent.com/assets/3285001/17468742/dd3352dc-5cf8-11e6-817f-0433aa4ee2c3.gif)

Still working on cleaning up the data over years. This graph, for some weird reasons, is not showing up the legend. Troubleshooting is in progress.

**Comment by radhikapc** [comment]
![model-wanna-do](https://cloud.githubusercontent.com/assets/3285001/17650846/f697bb46-6225-11e6-969e-30ad1d5a6ee2.JPG)

I am trying to do something similar with QGIS and Carto, but I am stuck !

**Comment by radhikapc** [comment]
![tech-percent-increase](https://cloud.githubusercontent.com/assets/3285001/17651095/fc75f24c-622c-11e6-9ba0-fd0622387b4e.gif)

**Comment by radhikapc** [comment]
closing this as I have opened the story #233
