### ISSUE TITLE
Airbnb apartments in NYC

### ISSUE THREAD

**Issue by shuyao1201** [jsoma/playfair-projects#87]
![image](https://cloud.githubusercontent.com/assets/19495692/17282991/c01abbba-5779-11e6-9795-a439e95b9d7d.png)

# Story issue checklist

My pitch was: #26 

- [x] My pitch has been approved (see `PITCHING.md`)
- [x] My story issue links to my pitch issue
- [x] I link to my finalized (ish) data source(s)
- [ ] I've included a brief summary of my story
- [x] I've included some possible headlines or findings
- [ ] I've included some links or images as inspiration (if you have any)
- [ ] I have received two comments of peer feedback
- [ ] I've included an update of my visualization/story in a comment
- [ ] I have received two comments of peer feedback after posting an update
- [ ] I have received editorial feedback

**Comment by juneeseo** [comment]
Nice graphics! Love the colors and little house on top.
I feel like it will be better to normalize the data rather than using raw numbers of listings since some neighborhood have larger housing stocks compare to other neighborhoods. You can find the housing stock data at American Factfinder.

**Comment by jowang0319** [comment]
Hey @shuyao1201 
Maybe you can show the  shared or entire room on the bar chart, make it stacked bars! (if I'm using the right word), and maybe also another percentage stacked bar.
Love the color change and the story!

**Comment by thisss** [comment]
Looks nice. I would take a short look at the color. The one on the top is probably not strong enough for print. And maybe you can make the letters a little bit smaller so that they are completely inside the bar of the graph.

**Comment by jsoma** [comment]
Pull request merged in #60

**Comment by shuyao1201** [comment]
![top10](https://cloud.githubusercontent.com/assets/19495692/17358903/3e927e06-5932-11e6-9204-64bb982b12db.png)
