### ISSUE TITLE
Rise in U.S. jail and prison population since 1980

### ISSUE THREAD

**Issue by snajmabadi** [jsoma/playfair-projects#98]
Dataset: http://www.bjs.gov/index.cfm?ty=kfdetail&iid=487

I intend to explore the change in inmate population since 1980, particularly focusing on what policy/political changes (i.e. three strikes law, etc.) overlap with any rise in inmate population during that time. I will also break down the data to show the portion of inmates that are in jails versus prisons, and state versus federal facilities. 

Dataset: http://www.bjs.gov/index.cfm?ty=pbdetail&iid=5519

I will explore how the 2014 inmate population breaks down across states (which states have the most/least inmates per capita, etc.). 

Possible headlines could include: 

- "x state has the most inmates per capita"
- "there are x times as many inmates in local jails as there are in prisons"
- "there was an x percent increase in inmate population between x year and x year"
- "the x percent increase in inmate population precedes x law" etc.

**Comment by snajmabadi** [comment]
# Pitch issue checklist

- [ ] My pitch issue has `[Pitch]` in the title
- [ ] My pitch issue has `[Data request]` in the title if I need additional data
- [ ] My pitch issue links to my data set
- [ ] My pitch issue explains what I'd like to explore in the data set
- [ ] My pitch issue includes multiple possible headlines
- [ ] My pitch issue includes any links/images I'm using as inspiration
- [ ] My pitch issue includes appropriate labels in the title such as `[Pitch]` and maybe `[Data Request]`
- [ ] I have received two comments of peer feedback on my pitch issue
- [ ] I have received editorial feedback on my pitch issue
- [ ] My pitch has been approved

**Comment by mercybenzaquen** [comment]
I think this is very VERY very interesting! Specially because you have a correlation that you are looking to find. I will look for the data I mentioned (breakdown of US states as if they were countries and the comparison of their inmate population with other countries) and will send it to you!

**Comment by oargueso** [comment]
I find your story can reveal a lot of insights. As a foreigner, I am not sure which is the difference between jails and prisons, so in my case a little bit of context about that could be useful. If you are going into gender breakdown, maybe checking which kind of offenses are more common for male and female inmates.

**Comment by jsoma** [comment]
Story created, closing
